#!/usr/bin/python3
import socket
import sys

# Forward all CLI args to the daemon (do not truncate optional flags like -d)
message = ",".join(sys.argv[1:])

client = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
try:
    client.connect("/tmp/sunshineVD.sock")
    client.sendall(message.encode('utf-8'))
finally:
    client.close()
